spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recauction_db
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: '587'
    username: testing.email.it2k2@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  host: http://tdawebservice.tech
  servlet:
    encoding:
      charset: utf-8
  error:
    path: /404

paypal:
  mode: sandbox
  client:
    app: Ad9tSzvE1MEuTpX22TvZVDq-AX-_Vge1uFyIZ6nQD7W9vlYkSBfnUtiyBctPEA5HxJ9b9z8Iz9mUmwbF
    secret: EDOwfQ0ECOQlF9OTW20vxBvnhYYzwAuN_FSrjiiLuBAsArU5JCiw1AzqZSwK5jssedsEhawrxjLmGeDm

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
